name: Scrape
on:
  workflow_dispatch:
  schedule:
    - cron: "5 10,22 * * *"
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Run scraper
        env:
          MONEYMAN_CONFIG: ${{ secrets.MONEYMAN_CONFIG }}
          TZ: "Asia/Jerusalem"
        run: |
          cat > /tmp/config.json << 'ENDOFCONFIG'
          ${{ secrets.MONEYMAN_CONFIG }}
          ENDOFCONFIG
          docker run --rm \
            -v /tmp/config.json:/config/config.json \
            -e MONEYMAN_CONFIG_PATH=/config/config.json \
            -e TZ="Asia/Jerusalem" \
            ghcr.io/daniel-hauser/moneyman:latest
